import { ClerkProvider } from "@clerk/nextjs"
import '../src/styles/app.css'


export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}) {
	return (
		<ClerkProvider>
			<html lang="en-AU">
				<head>
					<title>Daniel and Amy's Wedding</title>
				</head>
				<body>
					{children}
				</body>
			</html>
		</ClerkProvider>
			
	)
}